### ISSUE TITLE
[Meta] The overview

### ISSUE THREAD

**Issue by rodionovd** [rodionovd/cuckoo-osx-analyzer#2]
# Core Strategy
## Preparation
- setup directories to store the results in  
- _setup logging?_  
- Parse the passed config  
  - setup vm clock  
  - read the default injector lib path  
- remember a target path (file analysis) or URL (URL analysis)
## Run
- read an analysis package from the config or detect it automatically (e.g. based on the file name extension)  
- initialise all the auxiliary modules and launch them  
- run the decided analysis package  
  - it could return a list of PID that we’ll add into our watch list  (we won’t stop the analysis until all of these procs are alive)  
  - or it might return nothing and we’ll terminate the analysis process by the timeout (read it’s vale from the config)  
- _(in case of injection)_ listen to the injected library for analysis updates  
- upload analysis artefacts to the host  
- terminate all of the aux modules  
- kill the spawned processes if needed  
## Completion
-  _(in case of `dtrace`_) parse the dtrace output (files?) and figure them out; send the results to the host  
- dump files dropped to us from the host  

---
# Required Stuff
- Choose a way the analyser will talk to an injected process and receive updates back

**Comment by rodionovd** [comment]
For the reference: [win32 analyzer](https://github.com/cuckoobox/cuckoo/blob/master/analyzer/windows/analyzer.py) from Cuckoo Sandbox.  

I tried to replicate what the windows analyser does in general, let apart XMPRC communications and so on.

**Comment by jbremer** [comment]
Regarding XMLRPC. If you're able to keep that beast away that'd be great (I really, really want to replace it in the Windows analyzer as well as it is terrible).

**Comment by rodionovd** [comment]
Yeah, I too don't like it. Don't know, maybe I'll try using some unix pipes or XPC. Yeah, XPC looks good to me: even the OS X itself (e.g. all deamons) use it for communication between processes. I'm sure there's some Python API for it as well.

**Comment by phretor** [comment]
@rodionovd regarding dtrace/dtruss output parsing, I've just committed (on my fork, can send you a pull request if you want to integrate) a bunch of parsers that serialize the output of relevant tools (e.g., `dtrace`, `fslogger`, `nm`, `otool`) into Python dicts, which should be easy to adapt to specific formats.

**Comment by jbremer** [comment]
Awesome work @phretor, surely that could be useful for @rodionovd :)

**Comment by rodionovd** [comment]
Hi @phretor! Your work look great :+1: I'll definitely take a look.  

That said, I'm not quite sure if I should integrate them right now, because, well, I don't even know if `dtrace` is a good fit for Cuckoo (maybe we'll switch to something else, idk).  
But I'll sertantly have to deal with `otool` and `nm` so your parsers're gonna save me a lot of time! Thank you :-)

**Comment by phretor** [comment]
@rodionovd which other options are you considering apart from `dtrace`? I've been playing with QTrace, but it's quite heavy.

**Comment by rodionovd** [comment]
@phretor I'm also considering a library that would be injected into a target process for intercepting (hooking) any functions/API calls we'll need to watch.

**Comment by phretor** [comment]
@rodionovd I see. That'd follow the "tradition" of Cuckoo. However, wouldn't that be as evadable as `dtrace`? I understand such an approach on Windows, where there is no built-in tracing module in the kernel.

**Comment by rodionovd** [comment]
@phretor yeah, my thoughts are the same: it's better to take advantage of a built-in thing instead of reinventing it ourselves.   

Although, injecting our own code would give us more control over the target: we'd be able to fake some API calls' results and see what the target does. I'm not sure that it's a real world scenario, though :)

---

So, I'll try to implement the analyser using `dtrace`-stuff only first.
