### ISSUE TITLE
autoprobes.py => join similar probes together

### ISSUE THREAD

**Issue by rodionovd** [rodionovd/cuckoo-osx-analyzer#28]
For example, probes with the same signatures can be joined together in the following way:  

``` dtrace
/* Both foo() and bar() have this signature: (int, char *) -> int */
pid$target::foo:entry,
pid$target::bar:entry
{
    /* ... */
}

pid$target::foo:return,
pid$target::bar:return
{
    /* ... */
    printf(/*(int, char *) -> int*/);
     /* ... */
}
```

**Comment by jbremer** [comment]
Be cautious here, some probes may need extra processing (e.g., file paths, buffers, etc), so then I don't think you'll want to merge it :-)

**Comment by rodionovd** [comment]
You're right: there're edge cases (for example, I have already [hardcoded the `execve()` probe](https://github.com/rodionovd/cuckoo-osx-analyzer/blob/master/analyzer/darwin/lib/dtrace/apicalls.d#L75) for that reason).
But I don't actually perform any _real_ processing on `dtrace`'s side (this'd slow it down) — the analyzer does everything. 
I'll think what can be done here…

**Comment by rodionovd** [comment]
Well, I don't think we actually need this right now: things works pretty well even without grouping.
