### ISSUE TITLE
Bootstrapping

### ISSUE THREAD

**Issue by rodionovd** [rodionovd/cuckoo-osx-analyzer#5]
Need a bootstrap script that would integrate the analyser into an existing/new Cuckoo Sandbox repository clone automatically.  

Here're the steps required so far:  

``` bash
# $ git clone https://github.com/cuckoobox/cuckoo/ ~/projects/cuckoo
$ cd ./cuckoo-osx-analyzer
$ ln -s ./analyzer/darwin/ ~/projects/cuckoo/analyzer/
```

**Comment by jbremer** [comment]
This is pretty much what I do myself as well to test the Windows monitor. Alternatively you might want to use a symlink to make the "process" of bootstrapping transparantly :)

**Comment by rodionovd** [comment]
@jbremer ah, symlinking is a great idea! Actually, without it I'll have to run the script after every change to the analyser.  

Thanks!

**Comment by rodionovd** [comment]
Well, I guess since there're few steps required for integrating, there's no need for a script.  

_P.S. I wrote a little helper for bootstrapping a guest machine instead:_   https://github.com/rodionovd/cuckoo-osx-analyzer/blob/master/scripts/bootstrap_guest.sh
