### ISSUE TITLE
Add timeout to dtrace wrappers

### ISSUE THREAD

**Issue by rodionovd** [rodionovd/cuckoo-osx-analyzer#7]
Since some targets may run forever, we need to set a timeout value for `dtrace` tracing process, so it will only run for `X` seconds and no longer.

**Comment by jekil** [comment]
Timeout are defined in cuckoo.conf and they should be respected by all analyzers

**Comment by rodionovd** [comment]
@jekil sure! I'm working on it right now.

**Comment by rodionovd** [comment]
I guess I've done with it (as for 99a42febdbdcf3351d475472960d74647538c4d1)
