### ISSUE TITLE
Send analysis results to host [BSON]

### ISSUE THREAD

**Issue by rodionovd** [rodionovd/cuckoo-osx-analyzer#8]
Since we're using `dtrace` for analysing now, we have to form and upload the results from analyzer itself. I guess there's a Python library for handling BSON (e.g. [PyMongo](http://api.mongodb.org/python/current/) has `bson` module).

---

P.S. I've been working on the analyser [here](/rodionovd/cuckoo-osx-analyzer/tree/analyzer-in-wild), but it's not complete yet.

**Comment by phretor** [comment]
@rodionovd I'm also working on the analyzer on [my fork](https://github.com/phretor/cuckoo-osx-analyzer) but I still have to figure out. At this point I support full tracing, saving the trace on a temp file along with the stdout/stderr of the traced process.

I'm now figuring out how an analyzer (e.g., windows' analyzer) normally streams data back to the host, in which format, and so on.

**Comment by jbremer** [comment]
Connects to the host using a tcp connection and sends bson objects. For inspiration on our logging objects with bson you can look at this function: https://github.com/jbremer/monitor/blob/master/src/log.c#L279 and actually you'll also need this one https://github.com/jbremer/monitor/blob/master/src/log.c#L184

**Comment by rodionovd** [comment]
@phretor 

> I'm now figuring out how an analyzer (e.g., windows' analyzer) normally streams data back to the host, in which format, and so on.  

Well, AFAIK (should @jbremer correct me if I'm wrong), but on Windows it's not the analyser that sends logs to the host, but the injected process itself (see https://github.com/cuckoobox/cuckoomon/blob/cccba1ae19755ab5e45327a9683d230897269e41/cuckoomon.c#L396).

**Comment by jbremer** [comment]
Yeah, this is the case on Windows although this is changing in the near future. I've already committed the code, but it's pushed upstream yet. Basically there were some issues with sockets being unstable at certain points in time (e.g., when exiting the process) so we moved from the connection from the injected process to sending the logs through a pipe to the analyzer which then forwards it to the host.
Perhaps a similar approach could work in Mac OS X as well (using unix pipes?) but for now just connect from the monitor/dtrace stuff, I guess.

**Comment by phretor** [comment]
@jbremer so, if I generalize correctly: this "sending the logs through a pipe to the analyzer" is essentially equal to (if not more reliable than) "writing the logs to a buffered file". If we take this as granted, we can then transfer the log files to the host once the analysis is over.

Second, with "just connect from the monitor/dtrace stuff" you mean, stream bson stuff to the host while tracing, right?

**Comment by KillerInstinct** [comment]
@phretor be careful with "end of analysis" submission. It should be taken into account that the guest VM could crash for any reason really (like if the software forces a reboot). If you wait until the end of analysis to send over behavioral logs, unless you catch and reconnect the guest, you won't get any data back at all if the guest goes down.

**Comment by phretor** [comment]
@KillerInstinct yes, of course my solution is very naïve with respect to this. Fortunately, `subprocess.Popen` supports pipes transparently as it does for files.

**Comment by jbremer** [comment]
Yeah, the issue with a file is that if there's a BSOD / kernel panic / reboot then Cuckoo will probably not be able to retrieve the logs, thus missing behavioral data.. :)
So yeah, what @rodionovd said.

**Comment by jbremer** [comment]
Do note that the logs themselves are exactly the same with the only difference that you send it on the go.
In other news, I don't think you need to do the proxy (pipe -> tcp) thing under Linux / Mac OS X, as send/recv are system calls, whereas in Windows there's some serious user mode complexity involved with them (which cause stability issues in certain edge cases as mentioned earlier).

**Comment by rodionovd** [comment]
@jekil @jbremer 
So [here](https://github.com/rodionovd/cuckoo-osx-analyzer/tree/feature/talking-with-host) I've got a working version of the analyser that sends results back to the Cuckoo. It's very basic for now (no arg names, missing ppid, no module names, etc), but it [kinda works](https://www.dropbox.com/s/l4et3s57vmnupoi/Cuckoo%20Sandbox_njk.pdf?dl=0).

The only trouble I run into is Windows' `FILETIME`: the win32 analyser sends timestamps in this format but we don't have it on OS X. Thus I'm not sure what I'm supposed to do about it. _(now I'm just [sending zeros](https://github.com/rodionovd/cuckoo-osx-analyzer/blob/d31fa8533ad6358704dd1cbc537386a3fb67fd13/analyzer/darwin/lib/core/host.py#L124) for "TimeLow" and "TimeHigh". I've also patched [these](https://github.com/cuckoobox/cuckoo/blob/master/modules/processing/behavior.py#L157) [two](https://github.com/cuckoobox/cuckoo/blob/master/modules/processing/behavior.py#L267) lines in Cuckoo's `behavior` module to ignore the time values — it fails otherwise)_.

**Comment by rodionovd** [comment]
>  The only trouble I run into is Windows' FILETIME

Nevermind, I've found [a handy script ](https://github.com/rodionovd/cuckoo-osx-analyzer/blob/master/analyzer/darwin/lib/core/filetimes.py) that converts unix timestamps to FILETIME, so it's not a problem anymore :smile:

**Comment by rodionovd** [comment]
I close this one, since it's already implemented (still has some `todo`s here and there, though)
